### ISSUE TITLE
dicek code ajaxchat and forum

### ISSUE THREAD

**Issue by protoxyde** [ntvy95/koutogima#1]
Hello,

I installed your extensions, however, no dice roll function is said to this extension. Tell me what is it precisely?

Thank you for I seek an extension to my forum to launch soon and the AjaxChat, eg [index] 1d10 [/ dice] or / roll 1d100

Thank you in advance for your response.
Regards.

**Comment by Galixte** [comment]
Salut @protoxyde,

tu devrais voir aussi avec l’auteur de Ajax Chat: https://github.com/LMOspaceace/ajaxchat.

Bonne continuation. ;)

**Comment by protoxyde** [comment]
Bonjour et merci.

Je vais aller voir cela avec lui.

a bientôt

**Comment by ntvy95** [comment]
I am very sorry for the late reply. It has been a while since my last check on anything related to PHPBB.
I do not know French so I am very sorry for not being able to read and reply any comments in French.
@protoxyde This dicek cannot work on any chat extension because chat message does not contain anything like post id. I suggest you to look at this extension: https://www.phpbb.com/community/viewtopic.php?f=456&t=2306161 if you can wait a little bit and your message cannot be edited or you are not looking for a perfect solution in case your message can be edited.
I have a copy of this extension and you can download it here: http://www.mediafire.com/download/w6g25hom4iu6abj/hanelyp.zip. However I do not recommend install it now due to security issue reported about this extension.

**Comment by Galixte** [comment]
i found the repository: https://github.com/hanelyp/fancydice/ thanks.
